# Generated by Django 4.2 on 2023-04-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(upload_to='project/files/uploads'),
        ),
    ]
